# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  CABAL_REINIT_CONFIG: y
  LC_ALL: C.UTF-8
  ENABLE_INSTALL: y
  STACK_UPGRADE: y
  CABAL_CHECK_RELAX: y
  CABAL_NO_SANDBOX: y
  CABAL_HACKAGE_MIRROR: 'hackage.haskell.org:http://hackage.fpcomplete.com'
  TOOLS_DIR: '/opt'
  PACKCHECK_GITHUB_URL: 'https://raw.githubusercontent.com/harendra-kumar/packcheck'
  PACKCHECK_GITHUB_COMMIT: 'c4faad78b3292136a40a228196c3da0e3cac6e0c'
  PACKCHECK_LOCAL_PATH: './packcheck.sh'
  BUILD: stack
  # Windows variables

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      echo "cha cha"
      bash -c "from bash: hello"
  - powershell: |
      Write-Host "hello world"
    displayName: PShell
      if not exist %PACKCHECK_LOCAL_PATH% curl -sSkL -o%PACKCHECK_LOCAL_PATH% %PACKCHECK_GITHUB_URL%/%PACKCHECK_GITHUB_COMMIT%/packcheck.sh
      if not exist %LOCAL_BIN% mkdir %LOCAL_BIN%
      where stack.exe || curl -sSkL -ostack.zip http://www.stackage.org/stack/windows-x86_64 && 7z x stack.zip stack.exe && move stack.exe %LOCAL_BIN%
      if defined STACKVER (stack upgrade --binary-only --binary-version %STACKVER%) else (stack upgrade --binary-only || ver > nul)
      stack --version
    env:
      PATH: "%PATH%;%APPDATA%\\local\\bin"
      LOCAL_BIN: "%APPDATA%\\local\\bin"
    displayName: Setup Stack
  - bash: |
      echo "From bash initial step"
    displayName: Bash test
  - script: |
      stack setup > nul
      for /f "usebackq tokens=*" %%i in (`where 7z.exe`) do set PATH7Z=%%i\..
      for /f "usebackq tokens=*" %%i in (`where git.exe`) do set PATHGIT=%%i\..
      chcp 65001 && stack exec bash -- -c "chmod +x %PACKCHECK_LOCAL_PATH%; %PACKCHECK_LOCAL_PATH% stack PATH=/usr/bin:\"%PATH7Z%\":\"%PATHGIT%\""
    env:
      PATH: "%PATH%;%APPDATA%\\local\\bin"
      LOCAL_BIN: "%APPDATA%\\local\\bin"
    displayName: Test script
