# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  CABAL_REINIT_CONFIG: y
  LC_ALL: C.UTF-8
  ENABLE_INSTALL: y
  STACK_UPGRADE: y
  CABAL_CHECK_RELAX: y
  CABAL_NO_SANDBOX: y
  CABAL_HACKAGE_MIRROR: 'hackage.haskell.org:http://hackage.fpcomplete.com'
  TOOLS_DIR: '/opt'
  PACKCHECK_GITHUB_URL: 'https://raw.githubusercontent.com/harendra-kumar/packcheck'
  PACKCHECK_GITHUB_COMMIT: 'c4faad78b3292136a40a228196c3da0e3cac6e0c'
  PACKCHECK_LOCAL_PATH: './packcheck.sh'
  BUILD: stack
  # Windows variables

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      echo "cha cha"
  - powershell: |
      Write-Host "hello world"
    displayName: PShell
  - bash: |
      echo "hell form bash"
      # If a custom stack-yaml is specified, replace the default with that
      if test -e "$STACK_YAML"; then rm -f stack.yaml && ln -sv $STACK_YAML stack.yaml; else true; fi
      unset STACK_YAML
      # Get packcheck if needed
      CURL=$(which curl)
      PACKCHECK_URL=${PACKCHECK_GITHUB_URL}/${PACKCHECK_GITHUB_COMMIT}/packcheck.sh
      if test ! -e "$PACKCHECK_LOCAL_PATH"; then $CURL -sL -o "$PACKCHECK_LOCAL_PATH" $PACKCHECK_URL; fi;
      chmod +x $PACKCHECK_LOCAL_PATH

      which 7z.exe || $CURL -sL -o "$PACKCHECK_LOCAL_PATH" "https://www.7-zip.org/a/7z1805-x64.exe"

      # This script is governed by various PACKCHECK envvars that are set above.
      # In addition, hpc-coveralls needs TRAVIS, TRAVIS_JOB_ID variables set by
      # the travis CI environment.
      echo $PATH
      bash -c "$PACKCHECK_LOCAL_PATH $BUILD"
      displayName: "Stack Build"
    env:
      BUILD: stack
      RESOLVER: lts-12
    displayName: Test
