pool:
  vmImage: ubuntu-16.04

steps:
- script: |
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack
- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies
- script: |
    # Build the package, its tests, and its docs and run the tests
    stack --no-terminal test --haddock --no-haddock-deps
  displayName: Test Package
